[root@ansible tasks]# cat main.yml
- name: disable system firewalld
  service: name=firewalld state=stopped
- name: diable selinux
  selinux: state=disabled
#- name: source nginx
#  shell: rpm -Uvh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
- name: install nginx
  yum: name={{ item }} state=latest
  with_items:
      - nginx
- name: write nginx confie file
  template: src=/root/nginx/roles/nginx/templates/nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf
- name: copy index.html to remote
  copy : ' src=/root/nginx/roles/nginx/files/index.html dest=/usr/share/html/index.html mode=0755' 
- name: restart nginx service
  service: name=nginx state=restartd
- name:  run the health check 
  shell: "sh /root/nginx/roles/nginx/files/health_check.sh {{ server_name }}" 
  delegate_to: localhost
  register: health_status
- debug: msg="{{ health_status.stdout }}"
