- name: disable system firewalld
  service：name=firewalld state=stopped
- name：diable selinux
  selinux state=disabled
- name: set nginx yum source
  yum: pkg=epel-release state=latest
- name: write nginx confie file
  template: src=/root/nginx_playbooks/roles/nginx/templates/nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf
- name:copy index.html to remote
  copy : 'remote_src=nop src=/root/nginx_playbooks/roles/nginx/file/index.html dest=/usr/share/html/index.html mode=0755' 
- name: restart nginx service
  service: name=nginx state=restartd
- name run the health check 
  shell: "sh /root/nginx_playbooks/roles/nginx/file/health_check.sh {{ server_name }}" 
  delegate_to: localhost
  register: health_status
- debug: msg="{{ health_status.stdout }}"
